### PR TITLE
MG-72 - Fix NamedQueryContext not returning sql.ErrNoRows

### LINKED ISSUE #72: Bug: NamedQueryContext does not return sql.ErrNoRows, causing incorrect error handling
### What were you trying to achieve?

I was trying to handle the case where a query returns no results using `sqlx.NamedQueryContext`. The expectation was that if no rows exist, it would return `sql.ErrNoRows`, allowing proper error handling.

### What are the expected results?

If no rows are returned, `NamedQueryContext` should allow proper detection of this case in the error handling logic.

### What are the received results?

Currently, `NamedQueryContext` does **not** return `sql.ErrNoRows`. Instead, it returns a valid `*sqlx.Rows` object with `nil` error. This means the following check will never trigger:
```
if err != nil {
    if err == sql.ErrNoRows {
        return bootstrap.Config{}, errors.Wrap(repoerr.ErrNotFound, err)
    }
}
```

Instead, the correct way to check for no results is via `row.Next()`:
```
if !row.Next() { // This will correctly detect no rows
    return bootstrap.Config{}, errors.Wrap(repoerr.ErrNotFound, row.Err())
}
```

### Steps To Reproduce

1. Execute a query with NamedQueryContext where no rows match.
2. Observe that err == nil, but row.Next() returns false.
3. The existing error check for sql.ErrNoRows never triggers, leading to incorrect error handling.

### In what environment did you encounter the issue?

Go version: 1.23.4
Magistrala version/commit: main

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by nnpvaan**
# What type of PR is this?

This is a bug fix because it fixes the following issue: #72

## What does this do?

- Fixes incorrect error handling when `NamedQueryContext` does not return `sql.ErrNoRows`.
- Ensures `row.Next()` is checked before calling StructScan().
- Returns `repoerr.ErrNotFound` wrapped with `sql.ErrNoRows` when there are no rows.

## Which issue(s) does this PR fix/relate to?

- Related Issue #72 
- Resolves #72 

## Have you included tests for your changes?

No (Existing tests should already cover this behavior. If needed, I can add specific tests.)

## Did you document any new/modified feature?

No (Bug fix, no new documentation needed.)

### CODE REVIEW

File: bootstrap/postgres/configs.go [hunk 1]
```diff
@@ -100,15 +100,11 @@ func (cr configRepository) RetrieveByID(ctx context.Context, domainID, id string
 	}
 	row, err := cr.db.NamedQueryContext(ctx, q, dbcfg)
 	if err != nil {
-		if err == sql.ErrNoRows {
-			return bootstrap.Config{}, errors.Wrap(repoerr.ErrNotFound, err)
-		}
-
```
Comment (dborovcanin) [inline bootstrap/postgres/configs.go:106]: Please do the same across other similar cases, such as L206.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: bootstrap/postgres/configs.go (hunk 1 above)
Comment (nnpvaan) [reply bootstrap/postgres/configs.go:106]: @dborovcanin Thanks for your comment. I did it, please help me review again

**Review by dborovcanin — APPROVED** [review]
