### PR TITLE
MG-406 - Fix `panic` issues in rules engine go script

### LINKED ISSUE #406: Bug: Panic in `go script`  in the rule engine causes the service to crash
### What were you trying to achieve?

I was trying type casting in the script but forgot to handle a panic

### What are the expected results?

errors in the script should not cause rules engine to stop

### What are the received results?

Image

### Steps To Reproduce

1. create a rule  in rules engine
2. cause a panic in the script

### In what environment did you encounter the issue?

In the cloud

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?

## Which issue(s) does this PR fix/relate to?

- Related Issue #406 
- Resolves #406

### CODE REVIEW

File: re/golang.go [hunk 1]
```diff
@@ -30,7 +30,17 @@ type message struct {
...
+func (re *re) processGo(ctx context.Context, details []slog.Attr, r Rule, msg *messaging.Message) (ret pkglog.RunInfo) {
+	defer func() {
+		if r := recover(); r != nil {
+			ret = pkglog.RunInfo{
+				Level:   slog.LevelError,
+				Details: details,
+				Message: fmt.Sprintf("panic in Go script: %v", r),
+			}
+		}
+	}()
```
Comment (dborovcanin) [inline re/golang.go:45]: Do we absolutely need to use `recover()`? Is there any other way to handle Yaegi error?

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: re/golang.go (hunk 1 above)
Comment (nyagamunene) [reply re/golang.go:45]: > Do we absolutely need to use `recover()`? Is there any other way to handle Yaegi error?

Yaegi doesn't convert runtime panics to errors - they propagate as real Go panics.

Comment (dborovcanin) [reply re/golang.go:45]: OK, please also check how this works with go routines; i.e. `recover()` works only from the same routine. We should probably prevent interpreter code to run `go` anyways; we don't want to spawn a goroutine from there.

File: re/golang.go [hunk 2]
```diff
@@ -31,6 +34,14 @@ type message struct {
 }
 
 func (re *re) processGo(ctx context.Context, details []slog.Attr, r Rule, msg *messaging.Message) (ret pkglog.RunInfo) {
+	if goKeywordRegex.MatchString(r.Logic.Value) {
```
Comment (dborovcanin) [inline re/golang.go]: This check should be added during rule creation, not when running execution.

**Review by dborovcanin — CHANGES_REQUESTED** [review]
