### PR TITLE
MG-225 - Fix schedule validation

### LINKED ISSUE #225: Bug: Failed to create rule
I am try to create rule but i get error "Failed to create rule with error "start_datetime must be greater than or equal to current time""
https://github.com/user-attachments/assets/07ea9034-8f7b-48f6-aa2c-07ecbc7b6ca2

### PR DESCRIPTION
**Pull request by nyagamunene**
# What type of PR is this?
This is a bug fix because it fixes the following issue: 
- Adds validation method to schedule

## What does this do?
Adds validation method to schedule

## Which issue(s) does this PR fix/relate to?

- Resolves #225

### CODE REVIEW

**Review by dborovcanin — CHANGES_REQUESTED** [review]
Let's take a simpler approach - just use if `!startDateTime.IsZero()`.
It's safer than pointers and has the same effect.

File: pkg/schedule/schedule.go [hunk 1]
```diff
@@ -93,19 +111,22 @@ func (s *Schedule) UnmarshalJSON(data []byte) error {
...
-	if err != nil {
-		return err
+	if aux.StartDateTime != "" {
+		startDateTime, err := time.Parse(time.RFC3339, aux.StartDateTime)
+		if err != nil {
+			return err
+		}
+		s.StartDateTime = &startDateTime
+	} else {
+		s.StartDateTime = nil
```
Comment (dborovcanin) [inline pkg/schedule/schedule.go]: Set it to nil by default, then inspect:
```go
s.StartDateTime = nil
if aux.StartDateTime... try and set
```
Also, rename `aux` to `temp`.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — CHANGES_REQUESTED** [review]
@nyagamunene Why are we returning AuthError for ruel in past here: https://github.com/nyagamunene/magistrala/blob/80fb733fb5be297811015fc2ce14d2540d44e224/re/api/endpoints_test.go#L208?
