### PR TITLE
MG-67 - Update Magistrala compose with SuperMQ compose

### LINKED ISSUE #67: Make Magistrala use SuperMQ Compose
### What were you trying to achieve?

Create a script to use SuperMQ compose in Magistrala, rather than copying it because maintenance will become a problem.

### What are the expected results?

I expect that `make run args=-d` updates compose with the latest SuperMQ and run Magistrala on top of it.

### What are the received results?

N/A

### Steps To Reproduce

N/A

### In what environment did you encounter the issue?

Latest Docker compose.

### Additional information you deem important

_No response_

### PR DESCRIPTION
**Pull request by felixgateru**
# What type of PR is this?
This is a refactor as it changes the Magistrala compose use the SuperMQ compose.

## What does this do?
This pr:
- Adds a `SuperMQ` package in `Magistrala`
- Updates the Magistrala Compose to include the SuperMQ compose.
- Removes redundant and repeated env variables.

## Which issue(s) does this PR fix/relate to?

- Resolves #67 

## Have you included tests for your changes?
No, this is manually tested.

## Did you document any new/modified feature?
No

### CODE REVIEW

**Comment by dborovcanin** [comment]
@felixgateru Please resolve conflicts.

**Review by arvindh123 — CHANGES_REQUESTED** [review]
Please include only the Docker folder and the .env file as a subtree. 

Additionally, provide documentation on how to add or update the subtree. For example, if the SuperMQ Docker folder is updated, outline the steps to synchronize those changes with the master branch

**Comment by arvindh123** [comment]
> Please include only the Docker folder and the .env file as a subtree.
> 
> Additionally, provide documentation on how to add or update the subtree. For example, if the SuperMQ Docker folder is updated, outline the steps to synchronize those changes with the master branch

We can make the subtree stick to specific tag or version of SMQ

If we need to change version to new version of SMQ, then we can send a PR with git subtree updating to newer version

File: scripts/supermq.sh [hunk 1]
```diff
@@ -0,0 +1,46 @@
...
+
+if [ -d "$DEST_FOLDER" ]; then
+    rm -r "$DEST_FOLDER"
+fi
+mkdir -p "$DEST_FOLDER"
+mv -f "$EXTRACTED_FOLDER/$DOCKER_FOLDER" "$DEST_FOLDER/$DOCKER_FOLDER"
+
+git add "$DEST_FOLDER/$DOCKER_FOLDER"
+if [ -n "$(git status --porcelain "$DEST_FOLDER/$DOCKER_FOLDER")" ]; then
+    git commit -m "chore: update SuperMQ dependency files"
```
Comment (arvindh123) [inline scripts/supermq.sh]: we can remove this , person who is updating the docker compose 
should do stage and commit manually

**Review by arvindh123 — CHANGES_REQUESTED** [review]

**Review by arvindh123 — CHANGES_REQUESTED** [review]
In magistrala dockers , except nginx and addons directory, I think rest of the directory can be removed. Please check and remove the directory if not needed

File: docker/supermq-docker-compose.override.yml [hunk 2]
```diff
@@ -0,0 +1,128 @@
...
+        source: ${SMQ_NGINX_SERVER_CLIENT_CA:-../../docker/ssl/certs/ca.crt}
+        target: /etc/ssl/certs/ca.crt
+      - type: bind
+        source: ${SMQ_NGINX_SERVER_DHPARAM:-../../docker/ssl/dhparam.pem}
+        target: /etc/ssl/certs/dhparam.pem
+    networks: !override
+      - magistrala-base-net
+    env_file: !override
+      - ./.env
+      - ../docker/.env
```
Comment (arvindh123) [inline docker/supermq-docker-compose.override.yml]: This should be `../../docker/.env` like nginx config, since project_directory is `../supermq/docker`

**Review by arvindh123 — CHANGES_REQUESTED** [review]
Please remove `docker/nginx/snippets` , `docker/ssl/authorization.js` and `docker/ssl/dhparam.pem` from magistrala

**Review by arvindh123 — CHANGES_REQUESTED** [review]
Do we need 
`SMQ_CERTS_` 
`SMQ_VAULT_` 
`SMQ_JOURNAL_`
In magistrala ?

**Comment by felixgateru** [comment]
> Do we need `SMQ_CERTS_` `SMQ_VAULT_` `SMQ_JOURNAL_` In magistrala ?

We need `SMQ_JOURNAL_` and `SMQ_CERTS` but this is updated with this:
https://github.com/absmach/magistrala/pull/75

I will remove the `SMQ_VAULT` ones

**Review by arvindh123 — APPROVED** [review]
ENV is have mixed of both SMQ and MG, We need to come up with better way for ENVs.
Lets to this later.

**Review by dborovcanin — CHANGES_REQUESTED** [review]
This is rather dangerous, let's not mess up with someone else's repository. Instead, let's do something like this (I may have missed some steps):
1. Shallow clone and use --sparse to download only Docker directory:
```bash
git clone --depth 1 --filter=blob:none --sparse https://github.com/absmach/supermq.git
cd supermq
git sparse-checkout set docker
```
Then, move this docker directory inside MG docker:
```bash
mv docker ../docker/supermq-docker
cd ..
rm -r supermq
```
Also, update Makefile to include SMQ overrides there.

**Review by dborovcanin — APPROVED** [review]

File: scripts/supermq.sh [hunk 3]
```diff
@@ -0,0 +1,40 @@
...
+SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
+cd "$SCRIPT_DIR" || exit 1
+
+if [ -n "$(git status --porcelain)" ]; then
+    echo "There are uncommitted changes. Please commit or stash them before running this script."
+    exit 1
+fi
+
+cleanup() {
+    rm -rf "$TEMP_DIR" "../$TEMP_DIR"
```
Comment (dborovcanin) [inline scripts/supermq.sh]: Is `"../$TEMP_DIR"` required?

File: scripts/supermq.sh [hunk 4]
```diff
@@ -0,0 +1,40 @@
...
+###
+# Fetches the latest version of the docker files from the SuperMQ repository.
+###
+
+set -e
+set -o pipefail
+
+REPO_URL=https://github.com/absmach/supermq
+TEMP_DIR="supermq"
+DOCKER_FOLDER="docker"
```
Comment (dborovcanin) [inline scripts/supermq.sh]: Use `DIR` instead of `FOLDER`.

File: scripts/supermq.sh [hunk 5]
```diff
@@ -0,0 +1,40 @@
...
+DEST_FOLDER="../../docker/supermq-docker"
```
Comment (dborovcanin) [inline scripts/supermq.sh]: Same.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

File: scripts/supermq.sh (hunk 3 above)
Comment (felixgateru) [reply scripts/supermq.sh]: I initially included it to clean up incase there was an error in sparse checkout or in moving the contents of the folder but i dont think it will be required.

**Review by arvindh123 — CHANGES_REQUESTED** [review]
Please fix CI

File: Makefile [hunk 6]
```diff
@@ -246,7 +246,10 @@ endif
 endif
 endif
 
-run: check_certs
+fetch_supermq:
+	@./scripts/supermq.sh
+
```
Comment (dborovcanin) [inline Makefile:251]: Add this to CI, so it performs chek if there are changes in the SMQ compose is up to date.

**Review by dborovcanin — CHANGES_REQUESTED** [review]

**Review by dborovcanin — APPROVED** [review]
